title: 幻欲恒
description: 学习 / 科研 / 工具 / 网址库
theme: minima

# 站点主地址（有自定义域名就写自己的）
url: "https://huanyuheng.com"

# 顶部导航栏要显示的页面
header_pages:
  - index.md
  - links.md
  - about.md
  - archive.md

# 首页文章显示摘要
show_excerpts: true
